"""
能の練習表作成システム 定数定義
"""

# 環境設定のデフォルト値
MAX_ROOMS = 5
MAX_SCENES = 6
MAX_PEOPLE = 9
MAX_TIMESLOTS = 2  # ceil(6/5) = 2 を追加
SESSION_DURATION = 60

# 場面の優先度
PRIORITY_HIGH = 5
PRIORITY_MEDIUM = 4
PRIORITY_NORMAL = 3
PRIORITY_LOW = 2

# 練習時間の制限
MIN_PRACTICE_TIME = 30
MAX_PRACTICE_TIME = 240

# 報酬設定（場面ベースシステム用）
REWARD_NEW_ASSIGNMENT = 20.0  # 新規割り当ての報酬
REWARD_REASSIGNMENT = 0.0  # 再割り当てでは報酬なし
REWARD_REPEAT_ACTION = -8.0
REWARD_STEP_PENALTY = -0.5  # ステップごとのペナルティ
REWARD_EPISODE_COMPLETION = 100.0  # エピソード完了報酬
REWARD_TIME_EFFICIENCY = 3.0
REWARD_SCENE_COMPLETION = 10.0  # 場面完了の報酬
REWARD_PERSON_CONFLICT = -2.0   # 人物競合のペナルティ

# 学習設定のデフォルト値
MAX_STEPS = 10000
MAX_ACTION_HISTORY = 10
COMPLETION_THRESHOLD = 1.0