apiVersion: v1
kind: Secret
metadata:
  name: tomosigoto-secret
  namespace: tomosigoto
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: ZGV2cGFzc3dvcmQxMjM=
  POSTGRES_DB: dG9tb3NpZ290bw==
  SECRET_KEY: ZGV2LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2Q=
