from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class AccountSettingHistoryRepositoryProtocol(Protocol):
    """AccountSettingHistoryRepository Protocol"""

    async def create_history_record(self, history_data: dict[str, Any]) -> dict[str, Any]: ...
    async def get_history_by_user_id(self, user_id: str, limit: int = 50) -> list[dict[str, Any]]: ...
    async def get_history_by_field(self, user_id: str, field_name: str, limit: int = 20) -> list[dict[str, Any]]: ...
    async def get_history_by_id(self, history_id: str) -> dict[str, Any] | None: ...
    async def update_history_record(self, history_id: str, history_data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete_history_record(self, history_id: str) -> bool: ...
    async def delete_history_by_user_id(self, user_id: str) -> bool: ...
    async def get_history_count(self) -> int: ...
    async def get_recent_changes(self, limit: int = 100) -> list[dict[str, Any]]: ...
