from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class AttendanceRepositoryProtocol(Protocol):
    """AttendanceRepository Protocol"""

    async def find_all(self) -> list[dict[str, Any]]: ...
    async def find_by_id(self, attendance_id: UUID) -> dict[str, Any]: ...
    async def find_by_practice_schedule(self, practice_schedule_id: UUID) -> list[dict[str, Any]]: ...
    async def find_by_user(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def find_by_practice_and_user(self, practice_schedule_id: UUID, user_id: UUID) -> dict[str, Any] | None: ...
    async def create(self, attendance_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, attendance_id: UUID, attendance_data: dict[str, Any]) -> dict[str, Any]: ...
    async def upsert(self, attendance_data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete(self, attendance_id: UUID) -> bool: ...
    async def get_attendance_summary(self) -> list[dict[str, Any]]: ...
    async def get_user_attendance_history(self) -> list[dict[str, Any]]: ...
