from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ContactRepositoryProtocol(Protocol):
    """ContactRepository Protocol"""

    async def find_all(self, user_id: str | None = None) -> list[dict[str, Any]]: ...
    async def find_by_id(self, contact_id: str) -> dict[str, Any]: ...
    async def create(self, contact_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, contact_id: str, contact_data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete(self, contact_id: str) -> bool: ...
