from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DepartmentRepositoryProtocol(Protocol):
    """DepartmentRepository Protocol"""

    async def get_all_departments(self) -> list[dict[str, Any]]: ...
    async def get_department_by_code(self, department_code: str) -> dict[str, Any] | None: ...
    async def get_department_by_id(self, department_id: str) -> dict[str, Any] | None: ...
    async def create_department(self, department_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_department(self, department_id: str, department_data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete_department(self, department_id: str) -> bool: ...
    async def get_departments_by_campus(self, campus: str) -> list[dict[str, Any]]: ...
    async def get_department_count(self) -> int: ...
