from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID
from datetime import date


@runtime_checkable
class MaterialsPlaylistRepositoryProtocol(Protocol):
    """MaterialsPlaylistRepository Protocol"""

    async def find_all(self) -> list[dict[str, Any]]: ...
    async def find_by_id(self, playlist_id: UUID) -> dict[str, Any]: ...
    async def create(self, playlist_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, playlist_id: UUID, playlist_data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete(self, playlist_id: UUID) -> bool: ...
    async def search(self, title: str | None = None, name: str | None = None, year: int | None = None) -> list[dict[str, Any]]: ...


@runtime_checkable
class MaterialsSubPlaylistRepositoryProtocol(Protocol):
    """MaterialsSubPlaylistRepository Protocol"""

    async def find_all(self, playlist_id: UUID) -> list[dict[str, Any]]: ...
    async def find_by_id(self, playlist_id: UUID, sub_playlist_id: UUID) -> dict[str, Any]: ...
    async def create(self, playlist_id: UUID, sub_playlist_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, playlist_id: UUID, sub_playlist_id: UUID, sub_playlist_data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete(self, playlist_id: UUID, sub_playlist_id: UUID) -> bool: ...
    async def search(self, playlist_id: UUID, title: str | None = None, phase: str | None = None, recorded_date_from: date | None = None, recorded_date_to: date | None = None) -> list[dict[str, Any]]: ...


@runtime_checkable
class MaterialsVideoRepositoryProtocol(Protocol):
    """MaterialsVideoRepository Protocol"""

    async def find_all(self, sub_playlist_id: UUID) -> list[dict[str, Any]]: ...
    async def find_by_id(self, sub_playlist_id: UUID, video_id: UUID) -> dict[str, Any]: ...
    async def create(self, sub_playlist_id: UUID, video_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, sub_playlist_id: UUID, video_id: UUID, video_data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete(self, sub_playlist_id: UUID, video_id: UUID) -> bool: ...
    async def search(self, sub_playlist_id: UUID, title: str | None = None, recorded_date_from: date | None = None, recorded_date_to: date | None = None) -> list[dict[str, Any]]: ...


@runtime_checkable
class MaterialsFavoriteRepositoryProtocol(Protocol):
    """MaterialsFavoriteRepository Protocol"""

    async def find_all(self) -> list[dict[str, Any]]: ...
    async def find_by_id(self, favorite_id: UUID) -> dict[str, Any]: ...
    async def create(self, favorite_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, favorite_id: UUID, favorite_data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete(self, favorite_id: UUID) -> bool: ...
    async def find_by_user_id(self, user_id: UUID) -> list[dict[str, Any]]: ...
    async def find_by_user_id_and_video_id(self, user_id: UUID, video_id: UUID) -> dict[str, Any]: ...
    async def delete_by_user_id_and_video_id(self, user_id: UUID, video_id: UUID) -> bool: ...
    async def find_favorite_videos_with_details(self, user_id: UUID) -> list[dict[str, Any]]: ...
