from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class MemberAssignmentRepositoryProtocol(Protocol):
    """MemberAssignmentRepository Protocol"""

    def find_all(self) -> list[dict[str, Any]]: ...
    def find_by_id(self, assignment_id: UUID) -> dict[str, Any] | None: ...
    def find_by_part_id(self, part_id: UUID) -> list[dict[str, Any]]: ...
    def find_by_user_id(self, user_id: UUID) -> list[dict[str, Any]]: ...
    def find_by_user_and_part(self, user_id: UUID, part_id: UUID) -> dict[str, Any] | None: ...
    def find_with_details(self, assignment_id: UUID | None = None, part_id: UUID | None = None, user_id: UUID | None = None) -> list[dict[str, Any]]: ...
    def create(self, assignment_data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, assignment_id: UUID, assignment_data: dict[str, Any]) -> dict[str, Any] | None: ...
    def delete(self, assignment_id: UUID) -> bool: ...
    def delete_by_user_and_part(self, user_id: UUID, part_id: UUID) -> bool: ...
    def count(self) -> int: ...
