from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class PartRepositoryProtocol(Protocol):
    """PartRepository Protocol"""

    def find_all(self) -> list[dict[str, Any]]: ...
    def find_by_id(self, part_id: UUID) -> dict[str, Any] | None: ...
    def find_by_name(self, part_name: str) -> dict[str, Any] | None: ...
    def create(self, part_data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, part_id: UUID, part_data: dict[str, Any]) -> dict[str, Any] | None: ...
    def delete(self, part_id: UUID) -> bool: ...
    def count(self) -> int: ...
    def find_active(self) -> list[dict[str, Any]]: ...
    def find_by_stage_id(self, stage_id: str) -> list[dict[str, Any]]: ...
