from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class PracticeScheduleRepositoryProtocol(Protocol):
    """PracticeScheduleRepository Protocol"""

    def find_all(self) -> list[dict[str, Any]]: ...
    def find_all_with_relations(self) -> list[dict[str, Any]]: ...
    def find_by_id(self, schedule_id: UUID) -> dict[str, Any]: ...
    def find_by_date(self, target_date: str) -> dict[str, Any]: ...
    def find_by_date_range(self, start_date: str, end_date: str) -> list[dict[str, Any]]: ...
    def find_by_date_range_with_relations(self, start_date: str, end_date: str) -> list[dict[str, Any]]: ...
    def create(self, schedule_data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, schedule_id: UUID, schedule_data: dict[str, Any]) -> dict[str, Any]: ...
    def delete(self, schedule_id: UUID) -> bool: ...
    def find_with_details(self, schedule_id: UUID) -> dict[str, Any]: ...
    def find_for_display(self, schedule_id: UUID) -> dict[str, Any]: ...
