from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class ScheduleAvailableVenueRepositoryProtocol(Protocol):
    """ScheduleAvailableVenueRepository Protocol"""

    def find_all(self) -> list[dict[str, Any]]: ...
    def find_all_with_details(self, limit: int = 100, offset: int = 0, schedule_id: UUID | None = None, venue_id: UUID | None = None) -> list[dict[str, Any]]: ...
    def count_all(self, schedule_id: UUID | None = None, venue_id: UUID | None = None) -> int: ...
    def find_by_id(self, schedule_venue_id: UUID) -> dict[str, Any] | None: ...
    def find_by_schedule(self, schedule_id: UUID) -> list[dict[str, Any]]: ...
    def find_by_venue(self, venue_id: UUID) -> list[dict[str, Any]]: ...
    def find_by_schedule_and_venue(self, schedule_id: UUID, venue_id: UUID) -> dict[str, Any] | None: ...
    def create(self, schedule_venue_data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, schedule_venue_id: UUID, update_data: dict[str, Any]) -> dict[str, Any]: ...
    def delete(self, schedule_venue_id: UUID) -> bool: ...
    def delete_by_schedule(self, schedule_id: UUID) -> int: ...
    def delete_by_venue(self, venue_id: UUID) -> int: ...
    def find_schedule_by_id(self, schedule_id: UUID) -> dict[str, Any] | None: ...
    def find_venue_by_id(self, venue_id: UUID) -> dict[str, Any] | None: ...
