from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class ScheduleTimeSlotRepositoryProtocol(Protocol):
    """ScheduleTimeSlotRepository Protocol"""

    async def find_all(self) -> list[dict[str, Any]]: ...
    async def find_by_id(self, time_slot_id: UUID) -> dict[str, Any] | None: ...
    async def find_by_schedule(self, schedule_id: UUID) -> list[dict[str, Any]]: ...
    async def count_all(self, schedule_id: UUID | None = None) -> int: ...
    async def create(self, time_slot_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, time_slot_id: UUID, update_data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete(self, time_slot_id: UUID) -> bool: ...
    async def delete_by_schedule(self, schedule_id: UUID) -> int: ...
    async def find_schedule_by_id(self, schedule_id: UUID) -> dict[str, Any] | None: ...
