from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class SessionRepositoryProtocol(Protocol):
    """SessionRepository Protocol (practice_schedule_repository.py 内の SessionRepository)"""

    def find_by_schedule(self, schedule_id: UUID) -> list[dict[str, Any]]: ...
    def find_by_id(self, session_id: UUID) -> dict[str, Any]: ...
    def create(self, session_data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, session_id: UUID, session_data: dict[str, Any]) -> dict[str, Any]: ...
    def delete(self, session_id: UUID) -> bool: ...
    def delete_by_schedule(self, schedule_id: UUID) -> bool: ...


@runtime_checkable
class SessionRepositoryNewProtocol(Protocol):
    """SessionRepository Protocol (session_repository.py 内の拡張版 SessionRepository)"""

    def find_all(self) -> list[dict[str, Any]]: ...
    def find_by_id(self, session_id: UUID) -> dict[str, Any] | None: ...
    def find_by_schedule(self, schedule_id: UUID) -> list[dict[str, Any]]: ...
    def find_with_details(self, limit: int = 100, offset: int = 0, schedule_id: UUID | None = None, part_id: UUID | None = None) -> list[dict[str, Any]]: ...
    def count_all(self, schedule_id: UUID | None = None, part_id: UUID | None = None) -> int: ...
    def create(self, session_data: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, session_id: UUID, session_data: dict[str, Any]) -> dict[str, Any]: ...
    def delete(self, session_id: UUID) -> bool: ...
    def delete_by_schedule(self, schedule_id: UUID) -> int: ...
    def delete_by_part(self, part_id: UUID) -> int: ...
    def find_schedule_by_id(self, schedule_id: UUID) -> dict[str, Any] | None: ...
    def find_part_by_id(self, part_id: UUID) -> dict[str, Any] | None: ...
    def find_venue_by_id(self, venue_id: UUID) -> dict[str, Any] | None: ...
