from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class SessionInstructorRepositoryProtocol(Protocol):
    """SessionInstructorRepository Protocol"""

    async def find_all(self) -> list[dict[str, Any]]: ...
    async def find_all_with_details(self, limit: int = 20, offset: int = 0, schedule_id: UUID | None = None, slot_order: int | None = None) -> list[dict[str, Any]]: ...
    async def count_all(self, schedule_id: UUID | None = None, slot_order: int | None = None) -> int: ...
    async def find_by_id(self, session_instructor_id: UUID) -> dict[str, Any] | None: ...
    async def find_by_schedule(self, schedule_id: UUID) -> list[dict[str, Any]]: ...
    async def find_by_schedule_and_slot(self, schedule_id: UUID, slot_order: int) -> list[dict[str, Any]]: ...
    async def find_by_attendance_id(self, attendance_id: UUID) -> list[dict[str, Any]]: ...
    async def find_by_schedule_slot_and_attendance(self, schedule_id: UUID, slot_order: int, attendance_id: UUID) -> dict[str, Any] | None: ...
    async def create(self, session_instructor_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, session_instructor_id: UUID, update_data: dict[str, Any]) -> dict[str, Any]: ...
    async def delete(self, session_instructor_id: UUID) -> bool: ...
    async def delete_by_schedule(self, schedule_id: UUID) -> int: ...
    async def delete_by_schedule_and_slot(self, schedule_id: UUID, slot_order: int) -> int: ...
    async def find_schedule_by_id(self, schedule_id: UUID) -> dict[str, Any] | None: ...
    async def find_schedule_available_venue_by_id(self, venue_id: UUID) -> dict[str, Any] | None: ...
    async def find_attendance_by_id(self, attendance_id: UUID) -> dict[str, Any] | None: ...
    async def find_instructor_candidates(self, practice_schedule_id: UUID) -> list[dict[str, Any]]: ...
