from __future__ import annotations

from typing import Any, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class StageRepositoryProtocol(Protocol):
    """StageRepository Protocol"""

    async def find_all(self) -> list[dict[str, Any]]: ...
    async def find_by_id(self, stage_id: UUID) -> dict[str, Any] | None: ...
    async def create(self, stage_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update(self, stage_id: UUID, stage_data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete(self, stage_id: UUID) -> bool: ...
    async def find_by_status(self, status: str) -> list[dict[str, Any]]: ...
    async def exists(self, stage_id: UUID) -> bool: ...
