from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class UserRoleRepositoryProtocol(Protocol):
    """UserRoleRepository Protocol"""

    async def get_role_by_user_id(self, user_id: str) -> dict[str, Any] | None: ...
    async def get_role_by_user_and_type(self, user_id: str, role_type: str) -> dict[str, Any] | None: ...
    async def create_role(self, role_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_role(self, user_id: str, role_data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete_role(self, user_id: str) -> bool: ...
    async def delete_role_by_type(self, user_id: str, role_type: str) -> bool: ...
    async def get_roles_by_type(self, role_type: str, include_hidden: bool = False) -> list[dict[str, Any]]: ...
    async def get_all_roles(self, include_hidden: bool = False) -> list[dict[str, Any]]: ...
    async def get_user_roles_with_instructor(self) -> list[dict[str, Any]]: ...
    async def update_instructor_flag(self, user_id: str, is_instructor: bool) -> dict[str, Any] | None: ...
    async def get_instructor_flag(self, user_id: str) -> bool: ...
