from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class UserRepositoryProtocol(Protocol):
    """UserRepository Protocol"""

    async def get_user_by_id(self, user_id: str) -> dict[str, Any] | None: ...
    async def get_user_by_email(self, email: str) -> dict[str, Any] | None: ...
    async def create_user(self, user_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_user(self, user_id: str, user_data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete_user(self, user_id: str) -> bool: ...
    async def get_all_users(self) -> list[dict[str, Any]]: ...
    async def get_user_count(self) -> int: ...
