from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class UserProfileRepositoryProtocol(Protocol):
    """UserProfileRepository Protocol"""

    async def get_profile_by_user_id(self, user_id: str) -> dict[str, Any] | None: ...
    async def get_profiles_by_user_ids(self, user_ids: list[str]) -> list[dict[str, Any]]: ...
    async def get_profile_by_student_id(self, student_id: str) -> dict[str, Any] | None: ...
    async def create_profile(self, profile_data: dict[str, Any]) -> dict[str, Any]: ...
    async def update_profile(self, user_id: str, profile_data: dict[str, Any]) -> dict[str, Any] | None: ...
    async def delete_profile(self, user_id: str) -> bool: ...
    async def check_student_id_exists(self, student_id: str, exclude_user_id: str | None = None) -> bool: ...
    async def get_profile_count(self) -> int: ...
    async def get_profiles_by_department(self, department_id: str) -> list[dict[str, Any]]: ...
    async def check_email_exists(self, email: str, exclude_user_id: str | None = None) -> bool: ...
    async def get_all_profiles_basic(self) -> list[dict[str, Any]]: ...
