from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class UserProfileRepositoryProtocol(Protocol):
    """UserProfileRepository Protocol"""

    def get_profile_by_user_id(self, user_id: str) -> dict[str, Any] | None: ...
    def get_profiles_by_user_ids(self, user_ids: list[str]) -> list[dict[str, Any]]: ...
    def get_profile_by_student_id(self, student_id: str) -> dict[str, Any] | None: ...
    def create_profile(self, profile_data: dict[str, Any]) -> dict[str, Any]: ...
    def update_profile(self, user_id: str, profile_data: dict[str, Any]) -> dict[str, Any] | None: ...
    def delete_profile(self, user_id: str) -> bool: ...
    def check_student_id_exists(self, student_id: str, exclude_user_id: str | None = None) -> bool: ...
    def get_profile_count(self) -> int: ...
    def get_profiles_by_department(self, department_id: str) -> list[dict[str, Any]]: ...
    def check_email_exists(self, email: str, exclude_user_id: str | None = None) -> bool: ...
    def get_all_profiles_basic(self) -> list[dict[str, Any]]: ...
