from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class VenueRepositoryProtocol(Protocol):
    """VenueRepository Protocol"""

    async def find_all(self) -> list[dict[str, Any]]: ...
    async def find_by_id(self, venue_id) -> dict[str, Any]: ...
    async def create(self, venue_data) -> dict[str, Any]: ...
    async def update(self, venue_id, venue_data) -> dict[str, Any]: ...
    async def delete(self, venue_id) -> bool: ...
